# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages

r:
  - oldrel
  - release
  - devel
  
before_install:
  - sudo apt-get update

warnings_are_errors: false

# Package 'XML' is not available for R old release version 3.6.3 on CRAN
r_github_packages:
  - cran/XML