usethis::use_data(.catalog.row.order1536,
                   .catalog.row.order192,
                   .to.reorder.192.for.plotting,
                   .catalog.row.order96,
                   .catalog.row.order.DNS.78,
                   .catalog.row.order.DNS.144,
                   .to.reorder.144.for.plotting,
                   .catalog.row.order.QUAD.136,
                   .order.for.QUAD136.plotting,
                   .catalog.row.order.ID,
                   .ct.96.row.headers,
                   .ct.192.row.headers,
                   .ct.1536.row.headers,
                   .ct.DNS78.row.headers,
                   .ct.DNS144.row.headers,
                   .ct.QUAD136.row.headers,
                   .ct.ID.row.headers,
                   .trans.ranges,
                   .old.trans.ranges,
                   .abundance.2bp,
                   .abundance.3bp,
                   .abundance.4bp,
                   .abundance.5bp,
                   empty.cats,
                   internal = TRUE,
                   overwrite = TRUE)
