usethis::use_data(catalog.row.order.SNS.1536,
                  catalog.row.order.SNS.192,
                  catalog.row.order.SNS.96,
                  catalog.row.order.DNS.78,
                  catalog.row.order.DNS.144,
                  catalog.row.order.DNS.136,
                  catalog.row.order.ID,
                  catalog.row.headers.SNS.96,
                  catalog.row.headers.SNS.192,
                  catalog.row.headers.SNS.1536,
                  catalog.row.headers.DNS.78,
                  catalog.row.headers.DNS.144,
                  catalog.row.headers.DNS.136,
                  catalog.row.headers.ID,
                  trans.ranges.GRCh37,
                  old.trans.ranges.GRCh37,
                  abundance.2bp.GRCh37,
                  abundance.3bp.GRCh37,
                  abundance.4bp.GRCh37,
                  abundance.5bp.GRCh37,
                  overwrite = TRUE)

usethis::use_data(to.reorder.SNS.192.for.plotting,
                  to.reorder.DNS.144.for.plotting,
                  order.for.DNS.136.plotting,
                  empty.cats,
                  internal = TRUE,
                  overwrite = TRUE)
