// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// segment_simple_cpp
Rcpp::List segment_simple_cpp(std::string ins_or_del, std::string string, std::string context);
RcppExport SEXP _ICAMS_segment_simple_cpp(SEXP ins_or_delSEXP, SEXP stringSEXP, SEXP contextSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type ins_or_del(ins_or_delSEXP);
    Rcpp::traits::input_parameter< std::string >::type string(stringSEXP);
    Rcpp::traits::input_parameter< std::string >::type context(contextSEXP);
    rcpp_result_gen = Rcpp::wrap(segment_simple_cpp(ins_or_del, string, context));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ICAMS_segment_simple_cpp", (DL_FUNC) &_ICAMS_segment_simple_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ICAMS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
