# justify_indel

# To test the code in this file try test_VCFsToCatalogs.R

#' Move the notional position of a deletion or insertion as far left as possible.
#'
#' @description
#' short_string should be generated by a deletion in long-str
#' at (1-based) position pos. If supplied, the expected_delta
#' should be the deleted sequence. If expected_delta is not
#' NULL, the function checks this and aborts if this is not
#' the case.
#'
#' Dually, pos is the 1-based position in short string
#' in front o which one can
#' make an insertion to get long_str.
#'
#' This funcition moves pos as far to left as possible so that a deletion
#' at that position still results in an edit of long_str
#' to generate short_str.
#'
#' @param long_str A single character string
#'
#' @param short_str A single character string.
#'
#' @param pos An integer; see the description
#'
#' @param expected_delta A single string; see the desctiption
#'
#' @return A list with elements leftmost_pos and del_string

justify_indel = function(long_str, short_str, pos, expected_delta = NULL) {
  requireNamespace("stringi")
  del_len = nchar(long_str) - nchar(short_str)

  if (!is.null(expected_delta)) {
    if (expected_delta != substr(long_str, pos, pos + del_len - 1)) {
      message(
        "expected_delta = ",
        expected_delta,
        " != substr(long_str, pos, pos + del_len - 1)) = ",
        substr(long_str, pos, pos + del_len - 1)
      )
      browser()
      stop()
    }
  }

  stopifnot(
    stringi::stri_sub_replace(
      long_str,
      from = pos,
      to = pos + del_len - 1,
      replacement = ""
    ) ==
      short_str
  )
  for (test_pos in (pos - 1):0) {
    if (
      stringi::stri_sub_replace(
        long_str,
        test_pos,
        test_pos + del_len - 1,
        replacement = ""
      ) !=
        short_str
    ) {
      break
    }
  }
  leftmost_pos = test_pos + 1
  return(
    list(
      leftmost_pos = leftmost_pos,
      del_str = stringi::stri_sub(
        long_str,
        leftmost_pos,
        leftmost_pos + del_len - 1
      )
    )
  )
}
