# justify_indel

# To test the code in this file try test_VCFsToCatalogs.R

#' Move the notional position of a deletion or insertion as far left as
#' possible.
#'
#' @description short_string should be generated by a deletion in long-str at
#' (1-based) position pos. If supplied, the expected_delta should be the deleted
#' sequence. If expected_delta is not NULL, the function checks this and aborts
#' if this is not the case.
#'
#' Dually, pos is the 1-based position in short string in front o which one can
#' make an insertion to get long_str.
#'
#' This funcition moves pos as far to left as possible so that a deletion at
#' that position still results in an edit of long_str to generate short_str.
#'
#' @param long_str A single character string
#'
#' @param short_str A single character string.
#'
#' @param pos An integer; see the description
#'
#' @param expected_delta A single string; see the description
#'
#' @return A list with elements
#'
#' * leftmost_pos
#'
#' * del_string
#'
#' * del_string_plus del_string plus one base to the left the poisiton of that
#' base to the left is leftmost_pos - 1
#'
#' * edge_warning See the third example. We are not sure how far to the left we
#'   could have moved the indel if we had more context on the left.
#'
#' * error if non-NULL we did not see the expected value for
#' expected_delta
#'
#' @examples
#' justify_indel("CAAAG", "CAAG", pos = 2, expected_delta = "A")
#' justify_indel("CAAAG", "CAAG", pos = 3, expected_delta = "A")
#' justify_indel("CACAG", "CAG", pos = 3, expected_delta = "CA")
#'
#' @export

justify_indel = function(long_str, short_str, pos, expected_delta = NULL) {
  requireNamespace("stringi")
  del_len = nchar(long_str) - nchar(short_str)

  if (!is.null(expected_delta)) {
    if (expected_delta != substr(long_str, pos, pos + del_len - 1)) {
      msg = paste0(
        "expected_delta = ",
        expected_delta,
        " != substr(long_str, pos, pos + del_len - 1)) = ",
        substr(long_str, pos, pos + del_len - 1)
      )
      return(list(error = msg))
    }
  }

  stopifnot(
    stringi::stri_sub_replace(
      long_str,
      from = pos,
      to = pos + del_len - 1,
      replacement = ""
    ) ==
      short_str
  )
  for (test_pos in (pos - 1):0) {
    if (
      stringi::stri_sub_replace(
        long_str,
        test_pos,
        test_pos + del_len - 1,
        replacement = ""
      ) !=
        short_str
    ) {
      break
    }
  }
  edge_warning = FALSE
  if (test_pos == 0) {
    # A problem: we ran off the left end.

    # We are not sure how far to the left we could have
    # moved the indel if we had more context in the
    # left.

    # We need to move one to right and set a warning
    test_pos = test_pos + 1
    edge_warning = TRUE
  }
  leftmost_pos = test_pos + 1
  return(
    list(
      leftmost_pos = leftmost_pos,
      del_str = stringi::stri_sub(
        long_str,
        leftmost_pos,
        leftmost_pos + del_len - 1
      ),
      del_str_plus = stringi::stri_sub(
        long_str,
        leftmost_pos - 1,
        leftmost_pos + del_len - 1
      ),
      edge_warning = edge_warning,
      error = NULL
    )
  )
}
