# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Segment a single indel using Rcpp interface
#'
#' This function provides direct C++ interface for indel segmentation without
#' calling an external binary via system2.
#'
#' @param ins_or_del Character indicating insertion ("i") or deletion ("d")
#' @param string A single indel sequence to segment (character scalar)
#' @param context A single flanking context sequence (character scalar)
#'
#' @return A list with the following elements:
#'   \item{unit}{Repeat unit sequence (character)}
#'   \item{unit_length}{Unit length (integer)}
#'   \item{internal_rep}{Internal repeat region (character)}
#'   \item{internal_reps}{Internal repeat count (integer)}
#'   \item{spacer}{Spacer sequence (character)}
#'   \item{spacer_length}{Spacer length (integer)}
#'   \item{prime3_rep}{3' flanking repeat region (character)}
#'   \item{prime3_reps}{3' flanking repeat count (integer)}
#'   \item{original_reps}{Original repeat count (integer)}
#'
#' @export
segment_simple_cpp <- function(ins_or_del, string, context) {
    .Call('_ICAMS_segment_simple_cpp', PACKAGE = 'ICAMS', ins_or_del, string, context)
}

